//user reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED"
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED"
export const SET_USER = "SET_USER"
export const LOADING_USER = "LOADING_USER"
//UI reducer types
export const SET_ERRORS = "SET_ERRORS"
export const LOADING_UI = "LOADING_UI"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_DATA = "LOADING_DATA"
export const STOP_LOADING_UI = "STOP_LOADING_UI"
//Data reducer types
export const SET_USERS = "SET_USERS"
export const SET_EVENTS = "SET_EVENTS"
export const ADD_EVENT = "ADD_EVENT"
export const REMOVE_EVENT = "REMOVE_EVENT"
export const SET_SUBJECTS = "SET_SUBJECTS"
export const SET_SUBJECT = "SET_SUBJECT"
export const CLEAR_SUBJECT = "CLEAR_SUBJECT"
export const SET_FINISHED = "SET_FINISHED"
export const SET_UNFINISHED = "SET_UNFINISHED"
